# This example uses YAML anchors which allows reuse of multiple keys 
# without having to repeat yourself.
# Also see https://github.com/Mic92/dotfiles/blob/master/nixos/.sops.yaml
# for a more complex example.
keys:
  - &admin_max age1z5qy8fnarchqsvzeuppq8xmalweknnmhfu2t5kkqfken6p72n4sqf4tqy2
  - &server_jockey age1d805x7m7hhygaa2uq4c49jpraugq82sm3r4dx7hpv3ajqmlwkgrqsn6dna
creation_rules:
  - path_regex: secrets/users/max(?:bolotin)?/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *admin_max
  - path_regex: secrets/hosts/jockey/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *server_jockey
