github_packages_token: ENC[AES256_GCM,data:1WEZN60i3REMCk3p2brCPzLkw71MOQOAK7ENY1OuHrnDWs2VuGWQ5Q==,iv:lFuU+OYc5oKEe5GVQJ07mJm3vu1FVP3tWkrnmwTH6Ik=,tag:fZpERrMkLxNUXHJB9zF97g==,type:str]
github_token: ENC[AES256_GCM,data:tw8p0lhx3IClQxg0ox9L4mlo5oQEAPI0JRBJLY8bFQuxBvllLdZ/Lw==,iv:fbkPA7MYNEM0Vq00yu/FtBsFGZ/ymwgIB+jeXTE3rZw=,tag:MqOAqRs1FXtUORKgoZNUJg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1z5qy8fnarchqsvzeuppq8xmalweknnmhfu2t5kkqfken6p72n4sqf4tqy2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJTmhXbUVZNGFrZ1c1VGV6
            UzVDK2Nvck1EUFRuWUl3UFVsTG1tenl5M1RFCk9kMjdlVXRkUjlsd0lpU0xlS1Ew
            UTNZWmdYaThRUmVXdXBFOHI5b3JoK00KLS0tIGpTYU8vQW40cE14T2hQakpSOGl0
            SFg1QVZzVi9lYVM0MVoyL1hSMU1IcG8Kji4CFS5iwZ17/dOIkDPwH0D75J9xmvXW
            Y4Vs9gNlj22lU61Bu9r9Fxno36F69OpFAyH4Umc/gZr7FLUKK7efTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-29T10:45:09Z"
    mac: ENC[AES256_GCM,data:24wDhspvrotKfSidf9tGHFbm2f8ggMItjhl3Vk1KF0z5Q7uKMIYjmXf9RvV+7V+vdHnqZ8PaRgYfc4F1+fSfYgYY+mOEdfKA/0MifW3Qo5ysFQPhEK/0BqThYubZRH/g0FQ6jLs53hT2MEJOczhAOZXZXxBAJ0Hg5Bc44JCiaJM=,iv:/VZ8zWLTVezBgn6l0x8frdN1AmbbHSRfXGgQMI3a1og=,tag:1gfAZhL0P9YUi0q5o2hYag==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
