local map = vim.keymap.set
local harpoon = require("harpoon")

if vim.fn.has("macunix") then
	map("n", "<M-h>", "<Cmd>TmuxNavigateLeft<CR>", { desc = "Move Left" })
	map("n", "<M-l>", "<Cmd>TmuxNavigateRight<CR>", { desc = "Move Right" })
	map("n", "<M-j>", "<Cmd>TmuxNavigateDown<CR>", { desc = "Move Down" })
	map("n", "<M-k>", "<Cmd>TmuxNavigateUp<CR>", { desc = "Move Up" })

	map("n", "<C-h>", function()
		harpoon:list():select(1)
	end)
	map("n", "<C-j>", function()
		harpoon:list():select(2)
	end)
	map("n", "<C-k>", function()
		harpoon:list():select(3)
	end)
	map("n", "<C-l>", function()
		harpoon:list():select(4)
	end)

	map("i", "<M-b>", "<C-b>")
	map("i", "<M-e>", "<C-e>")
	map("n", "<M-s>", "<C-s>")
	map("n", "<M-c>", "<C-c>")
	map("n", "<M-q>", "<C-q>")
	map("n", "<M-W>", "<C-W>")
	map("n", "<M-o>", "<C-o>")
	map("n", "<M-i>", "<C-i>")
	map("t", "<M-x>", "<C-x>")
	map("n", "<M-e>", "<C-e>")
else
	-- map("i", "<C-h>", "<Left>", { desc = "Move Left" })
	-- map("i", "<C-l>", "<Right>", { desc = "Move Right" })
	-- map("i", "<C-j>", "<Down>", { desc = "Move Down" })
	-- map("i", "<C-k>", "<Up>", { desc = "Move Up" })
	map("n", "<C-h>", "<Cmd>TmuxNavigateLeft<CR>", { desc = "Move Left" })
	map("n", "<C-l>", "<Cmd>TmuxNavigateRight<CR>", { desc = "Move Right" })
	map("n", "<C-j>", "<Cmd>TmuxNavigateDown<CR>", { desc = "Move Down" })
	map("n", "<C-k>", "<Cmd>TmuxNavigateUp<CR>", { desc = "Move Up" })

	map("n", "<M-h>", function()
		harpoon:list():select(1)
	end)
	map("n", "<M-j>", function()
		harpoon:list():select(2)
	end)
	map("n", "<M-k>", function()
		harpoon:list():select(3)
	end)
	map("n", "<M-l>", function()
		harpoon:list():select(4)
	end)
end
