vim.cmd("highlight clear")
vim.cmd("colorscheme gruber-darker")
vim.cmd("set background=dark")
vim.cmd("hi @property guifg=#cc8c3c")
vim.cmd("hi HLChunk1 guifg=#ffdd33")
vim.cmd("hi HLLineNum1 guifg=#ffdd33")
vim.cmd("hi FoldColumn guibg=#181818")