vim.cmd("highlight clear")
vim.cmd("colorscheme ayu-dark")
vim.cmd("set background=dark")
vim.cmd("hi Function guifg=#bfbdb6")
vim.cmd("hi HLChunk1 guifg=#e6b450")
vim.cmd("hi HLLineNum1 guifg=#e6b450")
vim.cmd("hi IncSearch guifg=#0b0e14")
vim.cmd("hi LineNr guifg=#475266")
vim.cmd("hi IncSearch guibg=#f29668")
vim.cmd("hi Visual guibg=#475266")